// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AccountAccessType string

const (
	AccountAccessType_CURRENT_ACCOUNT AccountAccessType = "CURRENT_ACCOUNT"
	AccountAccessType_ORGANIZATION    AccountAccessType = "ORGANIZATION"
)

type AuthenticationProviderTypes string

const (
	AuthenticationProviderTypes_AWS_SSO AuthenticationProviderTypes = "AWS_SSO"
	AuthenticationProviderTypes_SAML    AuthenticationProviderTypes = "SAML"
)

type DataSourceType string

const (
	DataSourceType_AMAZON_OPENSEARCH_SERVICE DataSourceType = "AMAZON_OPENSEARCH_SERVICE"
	DataSourceType_CLOUDWATCH                DataSourceType = "CLOUDWATCH"
	DataSourceType_PROMETHEUS                DataSourceType = "PROMETHEUS"
	DataSourceType_XRAY                      DataSourceType = "XRAY"
	DataSourceType_TIMESTREAM                DataSourceType = "TIMESTREAM"
	DataSourceType_SITEWISE                  DataSourceType = "SITEWISE"
	DataSourceType_ATHENA                    DataSourceType = "ATHENA"
	DataSourceType_REDSHIFT                  DataSourceType = "REDSHIFT"
	DataSourceType_TWINMAKER                 DataSourceType = "TWINMAKER"
)

type LicenseType string

const (
	LicenseType_ENTERPRISE            LicenseType = "ENTERPRISE"
	LicenseType_ENTERPRISE_FREE_TRIAL LicenseType = "ENTERPRISE_FREE_TRIAL"
)

type NotificationDestinationType string

const (
	NotificationDestinationType_SNS NotificationDestinationType = "SNS"
)

type PermissionType string

const (
	PermissionType_CUSTOMER_MANAGED PermissionType = "CUSTOMER_MANAGED"
	PermissionType_SERVICE_MANAGED  PermissionType = "SERVICE_MANAGED"
)

type Role string

const (
	Role_ADMIN  Role = "ADMIN"
	Role_EDITOR Role = "EDITOR"
	Role_VIEWER Role = "VIEWER"
)

type SamlConfigurationStatus string

const (
	SamlConfigurationStatus_CONFIGURED     SamlConfigurationStatus = "CONFIGURED"
	SamlConfigurationStatus_NOT_CONFIGURED SamlConfigurationStatus = "NOT_CONFIGURED"
)

type UpdateAction string

const (
	UpdateAction_ADD    UpdateAction = "ADD"
	UpdateAction_REVOKE UpdateAction = "REVOKE"
)

type UserType string

const (
	UserType_SSO_USER  UserType = "SSO_USER"
	UserType_SSO_GROUP UserType = "SSO_GROUP"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_UNKNOWN_OPERATION       ValidationExceptionReason = "UNKNOWN_OPERATION"
	ValidationExceptionReason_CANNOT_PARSE            ValidationExceptionReason = "CANNOT_PARSE"
	ValidationExceptionReason_FIELD_VALIDATION_FAILED ValidationExceptionReason = "FIELD_VALIDATION_FAILED"
	ValidationExceptionReason_OTHER                   ValidationExceptionReason = "OTHER"
)

type WorkspaceStatus string

const (
	WorkspaceStatus_ACTIVE                 WorkspaceStatus = "ACTIVE"
	WorkspaceStatus_CREATING               WorkspaceStatus = "CREATING"
	WorkspaceStatus_DELETING               WorkspaceStatus = "DELETING"
	WorkspaceStatus_FAILED                 WorkspaceStatus = "FAILED"
	WorkspaceStatus_UPDATING               WorkspaceStatus = "UPDATING"
	WorkspaceStatus_UPGRADING              WorkspaceStatus = "UPGRADING"
	WorkspaceStatus_DELETION_FAILED        WorkspaceStatus = "DELETION_FAILED"
	WorkspaceStatus_CREATION_FAILED        WorkspaceStatus = "CREATION_FAILED"
	WorkspaceStatus_UPDATE_FAILED          WorkspaceStatus = "UPDATE_FAILED"
	WorkspaceStatus_UPGRADE_FAILED         WorkspaceStatus = "UPGRADE_FAILED"
	WorkspaceStatus_LICENSE_REMOVAL_FAILED WorkspaceStatus = "LICENSE_REMOVAL_FAILED"
	WorkspaceStatus_VERSION_UPDATING       WorkspaceStatus = "VERSION_UPDATING"
	WorkspaceStatus_VERSION_UPDATE_FAILED  WorkspaceStatus = "VERSION_UPDATE_FAILED"
)
